CREATE TABLE MEDICAL_RECORDS (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  PATIENT_NAME VARCHAR(128) NOT NULL,
  DATE DATE,
  ADMISSION_NOTES VARCHAR(255),
  ONSERVICE_NOTES VARCHAR(255),
  PROGRESS_NOTES VARCHAR(255),
  PREOPERATIVE_NOTES VARCHAR(255),
  OPERATIVE_NOTES VARCHAR(255),
  POSTOPERATIVE_NOTES VARCHAR(255),
  PROCEDURE_NOTES VARCHAR(255),
  DELIVERY_NOTES VARCHAR(255),
  POSTPARTUM_NOTES VARCHAR(255),
  DISCHARGE_NOTES VARCHAR(255)
);